Develop
heimsfridur/java-filmorate pull request #21
Opened 2024-07-07 19:26 UTC by heimsfridur

2024-07-10 06:23 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<Event> getFeed(@PathVariable int id) {
В остальных методах можно тоже использовать примитивный тип int. Вообще везде где явно не требуется объектный тип, лучше использовать примитивные типы. Они занимают меньше памяти и для ее освобождения не используется сборщик мусора (Garbadge collector), который пусть на короткое время но прерывает выполнение программы.

2024-07-10 06:33 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Общепринято поля и переменные объявлять с базовым типом, в данном случае лучше
`private Set<Genre> genres = = new LinkedHashSet<>();`
И не понятно чем HashSet<>() не устроил. LinkedHashSet поддерживает связный список элементов набора в том порядке, в котором они вставлялись. Но эта возможность имеет свою цену, вставка в LinkedHashSet будет чуть медленней, чем в HashSet.

2024-07-10 06:39 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @PostMapping(value = "/directors", consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
Аннотация `@RestController`  по умолчанию предполагает что вход и на выход метода нужно преобразовать в json. Поэтому consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE можно не писать.
Можно совсем упростить до `@PostMapping("/directors")`

2024-07-10 06:56 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +            return getDirectorById(directorId);
Можно не делать доп запрос к БД  getDirectorById, а просто присвоить director.setId(directorId) и дальше return director.
Любое обращение к БД операция затратная и если можно не делать лишний запрос к БД, то лучше не делать.

2024-07-10 07:00 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/DirectorRowMapper.java
> +    public Director mapRow(ResultSet rs, int rowNum) throws SQLException {
int rowNum здесь зачем

2024-07-10 07:03 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    public List<Director> getDirectors() {
можно проще return jdbcTemplate.query("select * from DIRECTORS", mapper.mapRow);

2024-07-10 07:22 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/FilmRowMapper.java
> +    private final MpaStorage mpaStorage;
В мапперах не должно быть зависимостей и соответственно запросов к другим таблицам. Лучше в классе сервиса получить все необходимые наборы (genres, directors) и добавить их к фильму.
У мапперов зона ответственности очень узкая - что-то получил на вход, преобразовал и отдал на выход.

2024-07-10 07:34 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = """
Отлично, что используете текстовые блоки """
Но почему только в одном месте) Очень удобно из текстовых блоков копипастить запросы в среду или окно где тестируем запросы.

2024-07-10 07:52 UTC, VadimZharkov requested changes
Можно улучшить.

2024-07-10 20:22 UTC, heimsfridur commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
Привет!
Спасибо за комментарии здесь и на площадке Практикума. Поправили всё кроме этого. В тестах postman жанры в фильмах должны возвращаться в порядке увеличения их id, если не используем LinkedHashSet, то это условие не выполняется, поэтому оставили так.

2024-07-11 06:23 UTC, VadimZharkov approved these changes

2024-07-21 13:15 UTC, merged